apiVersion: v1
kind: Namespace
metadata:
  name: iicpc-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: contestants
---
# ServiceAccount for the Sandboxing Engine
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandboxing-engine-sa
  namespace: iicpc-system
---
# Role allowing Pod and Job creation in the 'contestants' namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: contestant-manager
  namespace: contestants
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
# Bind the Role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandboxing-engine-binding
  namespace: contestants
subjects:
  - kind: ServiceAccount
    name: sandboxing-engine-sa
    namespace: iicpc-system
roleRef:
  kind: Role
  name: contestant-manager
  apiGroup: rbac.authorization.k8s.io
